services:
  mongo_test_one:
    image: mongo
    container_name: mongo_test_one_container
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/keyfile']
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4567890321
    ports:
      - '27017:27017'
    volumes:
      - mongo_test_one_data:/data/db
      - ./mongo-keyfile:/data/keyfile:ro

  mongo_test_two:
    image: mongo
    container_name: mongo_test_two_container
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/keyfile']
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4567890321
    ports:
      - '27018:27017'
    volumes:
      - mongo_test_two_data:/data/db
      - ./mongo-keyfile:/data/keyfile:ro

  mongo_init_replica:
    image: mongo
    depends_on:
      - mongo_test_one
      - mongo_test_two
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to be ready...' &&
        until mongosh --host mongo_test_one:27017 -u admin -p 4567890321 --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do sleep 2; done &&
        until mongosh --host mongo_test_two:27017 -u admin -p 4567890321 --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do sleep 2; done &&
        echo 'Both nodes are up, initiating replica set...' &&
        mongosh --host mongo_test_one:27017 -u admin -p 4567890321 --authenticationDatabase admin --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo_test_one:27017\" },
              { _id: 1, host: \"mongo_test_two:27017\" }
            ]
          })
        ' || true
      "

  node_server_test:
    build:
      context: .
      dockerfile: Dockerfile.Test
    container_name: node_server_test_container
    env_file:
      - .env.test
    ports:
      - '8000:8000'
    depends_on:
      - mongo_test_one
      - mongo_test_two
      - mongo_init_replica
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e "fetch(''http://127.0.0.1:8000/'').then(res => (res.ok ? process.exit(0) : process.exit(1))).catch(() => process.exit(1));"'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_test_one_data:
  mongo_test_two_data:
