name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/os-release

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Generate and set permissions for Mongo keyfile
        run: |
          openssl rand -base64 1024 > ./mongo-keyfile
          chmod 400 ./mongo-keyfile
          cat ./mongo-keyfile  # Debug: Show keyfile content

      - name: Install dependencies
        run: npm i -g pnpm && pnpm i

      - name: Run tests
        run: pnpm run test
