name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Generate mongo keyfile
        run: |
          openssl rand -base64 756 > mongo-keyfile
          chmod 600 mongo-keyfile

      - name: Install dependencies
        run: npm install -g pnpm && pnpm i

      - name: Run tests
        run: pnpm run test
